name: Build Release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['amd64', '386', 'arm64']
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: WillAbides/setup-go-faster@v1.19.0
        with:
          go-version: 'stable'
      - name: Setup Env
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          bc gcc libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb
      - name: Setup fyne
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true
      - name: Package
        run: fyne-cross windows -arch=${{ matrix.arch }}
      - name: Compress
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/dist
          unzip ${GITHUB_WORKSPACE}/fyne-cross/dist/windows-${{ matrix.arch }}/chrome_updater.exe.zip -d ${GITHUB_WORKSPACE}/fyne-cross/dist/windows-${{ matrix.arch }}
          mv -f ${GITHUB_WORKSPACE}/fyne-cross/dist/windows-${{ matrix.arch }}/chrome_updater.exe ${GITHUB_WORKSPACE}/dist/chrome_updater.exe
          if [ ${{ matrix.arch }} != 'arm64' ]; then
             upx -9 ${GITHUB_WORKSPACE}/dist/chrome_updater.exe
          fi
          zip -rj ${GITHUB_WORKSPACE}/dist/chrome_updater-windows-${{ matrix.arch }}.zip ${GITHUB_WORKSPACE}/dist/chrome_updater.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.arch }}
          path: dist/chrome_updater-windows-${{ matrix.arch }}.zip

  Release:
    needs: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*